### ISSUE TITLE
Unnecessary whitespace in hyperlinks

### ISSUE THREAD

**Issue by archimag** [willijar/cl-docutils#4]
For external hyperlinks having a line break before URI, for example

```
`target 
<http://www.example.org>`_
```

when generating HTML will be placed unnecessary whitespace, for example

```
<span>target </span>
```

**Comment by willijar** [comment]
Dear Andrey,

I have patched the parser to remove trailing whitespace from the text
components of inline references.

Regards,
John Williams

On 10 January 2013 15:31, Andrey Moskvitin notifications@github.com wrote:

> For external hyperlinks having a line break before URI, for example
> 
> `target
> <http://www.example.org>`_
> 
> when generating HTML will be placed unnecessary whitespace, for example
> 
> <span>target </span>
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/willijar/cl-docutils/issues/4.

## 

John Williams       Mobile: 07413597655
16 Park Avenue    Tel: 0121 709 4707
Solihull B91 3EJ

**Comment by archimag** [comment]
Great! Thank you!
